"""Render the whole-picture SQLite schema as one SQL document.

The DDL is deliberately owned per module (``CREATE TABLE IF NOT EXISTS`` +
each module's migrate); no single place in the runtime holds the full
picture. This module rebuilds it: apply every schema step to a throwaway
database in a temp directory, attribute each object to the step that
created it (``sqlite_master`` diff), and render the verbatim DDL grouped
by source module.

``docs/db-schema.sql`` is the committed output; ``scripts/regen_db_schema.py``
writes it and ``tests/test_db_schema_drift.py`` keeps it honest.

Never instantiate store *classes* here (``NodeStore()`` and friends reach
the real ``~/.persome`` via ``fts.cursor()``) — only module-level
``ensure_*(conn)`` functions against the throwaway connection. As a
backstop, ``render_schema_sql`` also points ``PERSOME_ROOT`` at the temp
directory for its whole run, so even a migrate that consults ``paths``
(e.g. evomem's pre-migration snapshot) cannot escape to the real store.
"""

from __future__ import annotations

import os
import sqlite3
import tempfile
from collections.abc import Callable
from pathlib import Path

_HEADER = """\
-- Generated by scripts/regen_db_schema.py — DO NOT EDIT.
-- Regenerate after changing any store DDL:
--
--     uv run python scripts/regen_db_schema.py
--
-- Source of truth stays in the per-module stores (CREATE TABLE IF NOT
-- EXISTS + per-module migrates); this file is the committed whole-picture
-- reference, guarded by tests/test_db_schema_drift.py.
"""

_TYPE_RANK = {"table": 0, "index": 1, "trigger": 2, "view": 3}


def _objects(conn: sqlite3.Connection) -> dict[tuple[str, str], str]:
    rows = conn.execute(
        "SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL"
    ).fetchall()
    return {(str(r[0]), str(r[1])): str(r[2]) for r in rows}


def _shadow_names(conn: sqlite3.Connection) -> set[str]:
    """Storage tables SQLite manages for virtual tables (FTS5 etc.)."""
    rows = conn.execute("SELECT name FROM pragma_table_list WHERE type = 'shadow'").fetchall()
    return {str(r[0]) for r in rows}


def _banner(title: str) -> str:
    bar = "-- " + "=" * 60
    return f"{bar}\n-- {title}\n{bar}\n"


def _render_section(
    title: str,
    keys: list[tuple[str, str]],
    objects: dict[tuple[str, str], str],
    shadow: set[str],
) -> str:
    # A key may have been dropped or recreated by a later step: render only
    # what survives in the final schema, and hide SQLite-managed shadows.
    keys = [
        k
        for k in sorted(keys, key=lambda k: (_TYPE_RANK.get(k[0], 9), k[1]))
        if k in objects and k[1] not in shadow
    ]
    if not keys:
        return ""
    lines = [f"-- ---- {title} ----", ""]
    for key in keys:
        lines.append(f"{objects[key]};")
        lines.append("")
    return "\n".join(lines)


def _index_db_steps() -> list[tuple[str, Callable[[sqlite3.Connection], None]]]:
    """Ordered schema steps for ``index.db`` beyond ``fts.connect()`` itself.

    Every module that creates tables lazily (outside ``fts.connect()``) must
    be registered here; ``test_every_create_table_in_source_is_dumped``
    fails the build otherwise.
    """
    from ..evomem import integrity as evo_integrity
    from ..evomem import store as evo_store
    from . import (
        contradictions,
        memory_deltas,
        parser_ticks,
        relation_edges,
        schema_faces,
    )

    def _evomem(conn: sqlite3.Connection) -> None:
        conn.executescript(evo_store._CREATE_SQL)
        evo_store._migrate(conn)

    return [
        ("store/relation_edges.py", relation_edges.ensure_schema),
        ("store/contradictions.py", contradictions.ensure_schema),
        ("store/memory_deltas.py", memory_deltas.ensure_schema),
        ("store/parser_ticks.py", parser_ticks.ensure_schema),
        ("store/schema_faces.py", schema_faces.ensure_schema),
        ("evomem/store.py", _evomem),
        ("evomem/integrity.py", evo_integrity.ensure_check_runs_schema),
    ]


def render_schema_sql() -> str:
    from . import fts

    parts = [_HEADER]

    with tempfile.TemporaryDirectory(prefix="persome-schema-dump-") as tmp:
        tmp_path = Path(tmp)
        prev_root = os.environ.get("PERSOME_ROOT")
        os.environ["PERSOME_ROOT"] = str(tmp_path / "root")
        try:
            parts.append(_banner("index.db — the single main store (~/.persome/index.db, WAL)"))
            conn = fts.connect(tmp_path / "index.db")
            try:
                objects = _objects(conn)
                sections = [
                    (
                        "store/fts.py connect() — core schema + modules ensured on every connect",
                        list(objects),
                    )
                ]
                for title, apply in _index_db_steps():
                    before = set(objects)
                    apply(conn)
                    objects = _objects(conn)
                    sections.append((title, [k for k in objects if k not in before]))
                shadow = _shadow_names(conn)
                for title, keys in sections:
                    section = _render_section(title, keys, objects, shadow)
                    if section:
                        parts.append(section)
            finally:
                conn.close()

        finally:
            if prev_root is None:
                os.environ.pop("PERSOME_ROOT", None)
            else:
                os.environ["PERSOME_ROOT"] = prev_root

    return "\n".join(parts).rstrip() + "\n"
