const screen=document.getElementById("screen");const steps=document.getElementById("steps");
const labels=["Welcome","Permissions","Import","Build","Ready"];let step=0;let state=null;let selected=new Set();let selectionInitialized=false;let poll=null;
function esc(value){return String(value??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
async function api(path,options={}){const response=await fetch(`onboarding/${path}`,{headers:{"Content-Type":"application/json"},...options});if(!response.ok)throw new Error((await response.json()).detail||"Something went wrong");return (await response.json()).data}
function renderSteps(){steps.innerHTML=labels.map((label,index)=>`<button class="step-dot ${index<step?"done":""}" aria-label="${label}" ${index===step?'aria-current="step"':""} disabled></button>`).join("")}
function actions(back,next,label="Continue"){return `<div class="actions"><button class="link" data-action="${back?"back":"skip"}">${back?"Back":"Skip for now"}</button>${next?`<button class="primary" data-action="next">${label}</button>`:""}</div>`}
function welcome(){screen.innerHTML=`<p class="kicker">Private by design</p><h1>Meet the model that grows with you.</h1><p>Persome builds a personal model from your context, entirely on this Mac.</p><div class="body privacy"><span>⌁</span><span>No cloud account required. You choose every source.</span></div>${actions(false,true,"Get started")}`}
function permissions(){const p=state.permissions;const rows=[["Accessibility","Reads visible context. Persome cannot type or click.",p.accessibility],["Screen Recording","Used only for optional local OCR.",p.screen_recording]];screen.innerHTML=`<p class="kicker">Step 2 of 5</p><h1>Allow local context.</h1><p>Each permission stays under macOS control.</p><div class="body rows">${rows.map(([name,copy,value])=>`<div class="row"><span>${value==="granted"||value==="not_applicable"?"✓":"○"}</span><div><strong>${name}</strong><small>${copy}</small></div><button class="secondary" data-permission="${name}" ${value==="not_applicable"?"disabled":""}>${value==="granted"?"Granted":value==="not_applicable"?"Not needed":"Open Settings"}</button></div>`).join("")}</div><p id="permission-hint" class="error" hidden>Finish the requested permissions before continuing.</p>${actions(true,true)}`}
function imports(){const sources=state.sources;const available=new Set(sources.filter(source=>source.available!==false).map(source=>source.type));if(!selectionInitialized){for(const source of sources){if(source.type==="obsidian"&&source.available!==false)selected.add(source.type)}selectionInitialized=true}for(const source of [...selected]){if(!available.has(source))selected.delete(source)}screen.innerHTML=`<p class="kicker">Step 3 of 5</p><h1>Bring your history.</h1><p>Start your model with notes you already have.</p><div class="body rows">${sources.map(source=>`<label class="row"><input type="checkbox" data-source="${source.type}" ${selected.has(source.type)?"checked":""} ${source.available===false?"disabled":""}><div><strong>${esc(source.label)}</strong><small>${esc(source.detail)}</small></div><span class="status">${source.available===false?"Unavailable":source.type==="obsidian"?"Read-only":"Optional"}</span></label>`).join("")}</div><div class="privacy"><span>⌁</span><span>Your original files will not be changed.</span></div>${actions(false,true,"Build my model")}`}
function building(){screen.innerHTML=`<p class="kicker">Step 4 of 5</p><h1>Building your personal model.</h1><p id="task-message">${esc(state.task.message||"Preparing your history…")}</p><div class="progress"><i></i></div><div class="checks"><div class="check done">✓ <span>Source boundaries verified</span></div><div class="check ${state.task.stage!=="importing"?"done":""}">${state.task.stage!=="importing"?"✓":"○"} <span>Import existing history</span></div><div class="check ${state.task.stage==="complete"?"done":""}">${state.task.stage==="complete"?"✓":"○"} <span>Form your model</span></div></div><div class="privacy"><span>↻</span><span>Safe to close. Progress is stored locally.</span></div>${state.task.error?`<p class="error">${esc(state.task.error)}</p><div class="actions"><button class="secondary" data-action="retry">Choose sources again</button></div>`:""}`}
function ready(){const imported=state.task.stage==="complete";screen.innerHTML=`<p class="kicker">Ready</p><h1>${imported?"Your model has a head start.":"Persome is ready."}</h1><p>${imported?"Your selected history is now part of your model.":"You can import existing history whenever you are ready."}</p><div class="body checks">${imported?`<div class="check done">✓ <span>${state.task.imported||0} documents imported or updated</span></div><div class="check done">✓ <span>${state.task.unchanged||0} unchanged documents recognized</span></div>`:""}<div class="check done">✓ <span>Your source files stayed unchanged</span></div></div><div class="actions"><button class="link" data-action="restart">Review setup</button><a class="primary" href="./" style="display:grid;place-items:center;text-decoration:none">Open my model</a></div>`}
function render(){renderSteps();[welcome,permissions,imports,building,ready][step]()}
async function refresh(){state=await api("state");if(state.task.stage==="importing"||state.task.stage==="building"||state.task.stage==="failed"){step=3}if(state.task.stage==="complete"){step=4;clearInterval(poll)}render()}
async function startImport(){const items=[];for(const source of state.sources){if(!selected.has(source.type))continue;if(source.type==="obsidian")items.push({type:"obsidian"});else{const chosen=await api(`select-folder?source=${source.type}`,{method:"POST",body:"{}"});if(chosen.path)items.push({type:source.type,path:chosen.path})}}await api("import",{method:"POST",body:JSON.stringify({sources:items})});step=3;await refresh()}
document.addEventListener("change",event=>{const input=event.target.closest("[data-source]");if(input){input.checked?selected.add(input.dataset.source):selected.delete(input.dataset.source)}});
document.addEventListener("click",async event=>{const permission=event.target.closest("[data-permission]");if(permission&&permission.textContent!=="Granted"){await api(`open-settings?kind=${permission.dataset.permission.startsWith("Screen")?"screen_recording":"accessibility"}`,{method:"POST",body:"{}"});return}const button=event.target.closest("[data-action]");if(!button)return;if(button.dataset.action==="next"){if(step===1&&Object.values(state.permissions).some(value=>value==="denied")){document.getElementById("permission-hint").hidden=false;return}if(step===2){await startImport();return}step=Math.min(4,step+1)}if(button.dataset.action==="back")step=Math.max(0,step-1);if(button.dataset.action==="skip")step=step===2?4:Math.min(4,step+1);if(button.dataset.action==="restart")step=0;if(button.dataset.action==="retry")step=2;render()});
refresh().then(()=>{poll=setInterval(refresh,1500)}).catch(error=>{screen.innerHTML=`<h1>Persome could not load setup.</h1><p class="error">${esc(error.message)}</p>`});
