-- Generated by scripts/regen_db_schema.py — DO NOT EDIT.
-- Regenerate after changing any store DDL:
--
--     uv run python scripts/regen_db_schema.py
--
-- Source of truth stays in the per-module stores (CREATE TABLE IF NOT
-- EXISTS + per-module migrates); this file is the committed whole-picture
-- reference, guarded by tests/test_db_schema_drift.py.

-- ============================================================
-- index.db — the single main store (~/.persome/index.db, WAL)
-- ============================================================

-- ---- store/fts.py connect() — core schema + modules ensured on every connect ----

CREATE TABLE captures (
    rowid INTEGER PRIMARY KEY AUTOINCREMENT,
    id TEXT UNIQUE NOT NULL,
    timestamp TEXT NOT NULL,
    app_name TEXT,
    bundle_id TEXT,
    window_title TEXT,
    focused_role TEXT,
    focused_value TEXT,
    visible_text TEXT,
    url TEXT
);

CREATE VIRTUAL TABLE captures_fts USING fts5(
    app_name, window_title, focused_value, visible_text, url,
    content='captures', content_rowid='rowid',
    tokenize='unicode61 remove_diacritics 2'
);

CREATE VIRTUAL TABLE entries USING fts5(
    id UNINDEXED,
    path UNINDEXED,
    prefix UNINDEXED,
    timestamp UNINDEXED,
    tags,
    content,
    superseded UNINDEXED,
    tokenize = 'unicode61 remove_diacritics 2'
);

CREATE TABLE entry_metadata (
            entry_id    TEXT PRIMARY KEY,
            confidence  TEXT,
            conflicted  INTEGER NOT NULL DEFAULT 0,
            occurred_at TEXT
        );

CREATE TABLE entry_retrieval_stats (
    entry_id TEXT PRIMARY KEY,
    retrieval_count INTEGER NOT NULL DEFAULT 0,
    last_retrieved_at TEXT
);

CREATE TABLE entry_temporal (
            entry_id   TEXT PRIMARY KEY,
            valid_from TEXT NOT NULL,
            valid_until TEXT
        );

CREATE TABLE entry_vectors (
            entry_id    TEXT PRIMARY KEY,
            dim         INTEGER NOT NULL,
            model       TEXT NOT NULL,
            vector      BLOB NOT NULL,
            embedded_at TEXT NOT NULL
        );

CREATE TABLE files (
    path TEXT PRIMARY KEY,
    prefix TEXT,
    description TEXT,
    tags TEXT,
    status TEXT,
    entry_count INTEGER,
    created TEXT,
    updated TEXT,
    needs_compact INTEGER DEFAULT 0
);

CREATE TABLE intents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,                 -- ISO8601 recognition time
    scope TEXT NOT NULL,              -- scene id: 'timeline' | <meeting-id> | ...
    kind TEXT NOT NULL,               -- open string; seed: meeting|calendar|reminder
    confidence REAL NOT NULL DEFAULT 0.0,
    status TEXT NOT NULL DEFAULT 'open',  -- open | armed | consumed | dismissed | expired | resolved | completed | failed
    rationale TEXT NOT NULL DEFAULT '',
    payload TEXT NOT NULL DEFAULT '{}',   -- JSON: kind-specific fields
    evidence TEXT NOT NULL DEFAULT '[]',  -- JSON: provenance list
    dedup_key TEXT NOT NULL DEFAULT '',   -- scope|kind|when_text|with — for idempotent persist
    created_at TEXT NOT NULL,
    dismissed_at TEXT,                    -- ISO8601 when the row transitioned to status='dismissed' (NULL otherwise); the kind-cooldown clock (#533) anchors on this, NOT ts (recognition time)
    completed_at TEXT,                    -- ISO8601 when the row transitioned to status IN (completed,failed) (NULL otherwise); reverse-loop: the accept→completed positive prior (_completed_prior) anchors on this, NOT ts

    fire_on TEXT NOT NULL DEFAULT '',     -- event-based intent: trigger event key ('' == immediate)
    fire_config TEXT NOT NULL DEFAULT '{}',  -- JSON: trigger params (bundle_id/app/...)
    fired_at TEXT,                        -- ISO8601 when the trigger fired (NULL until then)
    schema_sources TEXT NOT NULL DEFAULT '[]',  -- JSON: schema-*.md files injected when recognized (R4 provenance)
    resolved_at TEXT,                     -- ISO8601 deterministic parse of payload.when_text anchored at ts (NULL = unparsed)
    valid_until TEXT,                     -- ISO8601 expiry: resolved_at(+end) + kind grace (NULL = never expires)
    source_capture TEXT,                  -- capture-buffer file stem this intent was recognized FROM (#7 provenance; NULL = none/legacy → time-window join fallback)
    resolution_outcome TEXT,              -- evidence-driven auto-close outcome (done|rejected|superseded; NULL unless status='resolved')
    resolution_quote TEXT                 -- ≤120-char supporting quote for the evidence-driven close (NULL unless status='resolved')
);

CREATE TABLE projection_state (
    file_name    TEXT PRIMARY KEY,
    content_hash TEXT NOT NULL,
    projected_at TEXT NOT NULL
);

CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    start_time TEXT NOT NULL,
    end_time TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TEXT,
    last_error TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    flush_end TEXT,
    classified_end TEXT,
    pattern_detected_end TEXT,
    active_tick_bookmark TEXT
, total_cost_usd REAL, recognized_final_at TEXT);

CREATE TABLE sqlite_sequence(name,seq);

CREATE TABLE system_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE timeline_blocks (
    id TEXT PRIMARY KEY,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    timezone TEXT NOT NULL DEFAULT '',
    entries TEXT NOT NULL,
    apps_used TEXT NOT NULL,
    capture_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    helpful_intent_tags TEXT NOT NULL DEFAULT '[]',
    skill_hints TEXT NOT NULL DEFAULT '[]',
    action_trace TEXT NOT NULL DEFAULT '[]',
    focus_excerpt TEXT NOT NULL DEFAULT '',
    focus_structured TEXT NOT NULL DEFAULT '',
    attention_surface TEXT NOT NULL DEFAULT '',
    attention_confidence REAL NOT NULL DEFAULT 0.0,
    attention_rung TEXT NOT NULL DEFAULT '',
    UNIQUE(start_time, end_time)
);

CREATE TABLE vector_queue (
            entry_id    TEXT PRIMARY KEY,
            enqueued_at TEXT NOT NULL
        );

CREATE INDEX idx_captures_app ON captures(app_name);

CREATE INDEX idx_captures_ts  ON captures(timestamp);

CREATE INDEX idx_files_prefix ON files(prefix);

CREATE INDEX idx_files_status ON files(status);

CREATE INDEX idx_intents_dedup ON intents(dedup_key);

CREATE INDEX idx_intents_scope_ts ON intents(scope, ts DESC);

CREATE INDEX idx_intents_source_capture ON intents(source_capture);

CREATE INDEX idx_intents_status_ts ON intents(status, ts DESC);

CREATE INDEX idx_sessions_retry ON sessions(next_retry_at)
    WHERE status = 'failed';

CREATE INDEX idx_sessions_start ON sessions(start_time);

CREATE INDEX idx_sessions_status ON sessions(status);

CREATE INDEX idx_tlb_end ON timeline_blocks(end_time);

CREATE INDEX idx_tlb_start ON timeline_blocks(start_time);

CREATE TRIGGER captures_ad AFTER DELETE ON captures BEGIN
    INSERT INTO captures_fts(captures_fts, rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES ('delete', old.rowid, old.app_name, old.window_title, old.focused_value, old.visible_text, old.url);
END;

CREATE TRIGGER captures_ai AFTER INSERT ON captures BEGIN
    INSERT INTO captures_fts(rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES (new.rowid, new.app_name, new.window_title, new.focused_value, new.visible_text, new.url);
END;

CREATE TRIGGER captures_au AFTER UPDATE ON captures BEGIN
    INSERT INTO captures_fts(captures_fts, rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES ('delete', old.rowid, old.app_name, old.window_title, old.focused_value, old.visible_text, old.url);
    INSERT INTO captures_fts(rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES (new.rowid, new.app_name, new.window_title, new.focused_value, new.visible_text, new.url);
END;

-- ---- store/relation_edges.py ----

CREATE TABLE relation_edges (
    edge_id      TEXT PRIMARY KEY,
    src_identity TEXT NOT NULL,          -- 稳定 identity（person_graph 规范名 / PROJECT slug），非版本 node_id
    dst_identity TEXT NOT NULL,
    predicate    TEXT NOT NULL,          -- 6 谓词闭集之一
    label        TEXT,                   -- 自由文本关系（开集语义）
    valid_from   TEXT NOT NULL,          -- 有效时间起（ISO8601）
    valid_to     TEXT,                   -- NULL = 当前有效
    provenance   TEXT NOT NULL,          -- 'user_committed' | 'inferred'
    confidence   REAL NOT NULL,
    quote        TEXT,                   -- ≤120 字支撑原文（证据）
    status       TEXT NOT NULL,          -- MemoryStatus: 'shadow'|'active'|'superseded'|'archived'
    created_at   TEXT NOT NULL,          -- 事务时间（版本轴，不可变）
    observations INTEGER NOT NULL DEFAULT 1,  -- 强度=支撑该关系的证据数（event 蒸馏计数，单调不减）
    last_observed_at TEXT,              -- 最近一次证据强化时刻（ISO8601）
    recall_count INTEGER NOT NULL DEFAULT 0  -- 读也是强化（§3.3 testing effect）：树链走过这条边即 +1
, src_kind TEXT, dst_kind TEXT, polarity TEXT NOT NULL DEFAULT '0', source_kind TEXT, source_id TEXT, source_receipt TEXT);

CREATE INDEX ix_edges_dst ON relation_edges(dst_identity, valid_from);

CREATE INDEX ix_edges_src ON relation_edges(src_identity, valid_from);

-- ---- store/contradictions.py ----

CREATE TABLE memory_contradictions (
    pair_key    TEXT PRIMARY KEY,   -- sorted "a_id|b_id" — unordered-pair identity
    a_id        TEXT NOT NULL,
    b_id        TEXT NOT NULL,
    path        TEXT NOT NULL,      -- the memory file both facts live in
    a_body      TEXT NOT NULL,
    b_body      TEXT NOT NULL,
    reason      TEXT NOT NULL,      -- the judge's one-line why
    status      TEXT NOT NULL,      -- open | resolved | dismissed
    keep_id     TEXT,               -- resolve verdict: the entry the human kept
    created_at  TEXT NOT NULL,
    resolved_at TEXT
);

-- ---- store/memory_deltas.py ----

CREATE TABLE memory_deltas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    created_at TEXT NOT NULL,            -- ISO8601 consolidation time
    model TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'shadow',
    payload TEXT NOT NULL DEFAULT '{}',  -- post-gate delta JSON
    dropped INTEGER NOT NULL DEFAULT 0   -- items removed by the deterministic gates
);

CREATE INDEX idx_memory_deltas_created ON memory_deltas(created_at DESC);

CREATE INDEX idx_memory_deltas_session ON memory_deltas(session_id);

-- ---- store/parser_ticks.py ----

CREATE TABLE parser_ticks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,              -- ISO8601 window time (block start)
    bundle_id TEXT NOT NULL,       -- app bundle the outcome is attributed to
    outcome TEXT NOT NULL,         -- 'hit' | 'miss' | 'fallback'
    created_at TEXT NOT NULL
);

CREATE INDEX idx_parser_ticks_ts ON parser_ticks(ts DESC);

-- ---- store/recall_budget_ticks.py ----

CREATE TABLE recall_budget_ticks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,              -- ISO8601 assembly time
    scope TEXT NOT NULL,           -- recall scope (session-*, meeting-*, ...)
    max_chars INTEGER NOT NULL,    -- shared assembly ceiling
    used INTEGER NOT NULL,         -- chars admitted across all layers
    layers TEXT NOT NULL DEFAULT '{}',  -- JSON {layer: {admitted, admitted_chars, rejected, rejected_chars}}
    squeezed INTEGER NOT NULL DEFAULT 0, -- 1 when ANY layer rejected at least one text
    hints TEXT NOT NULL DEFAULT '[]',   -- JSON list of the call's hint terms (debugging telemetry)
    created_at TEXT NOT NULL
);

CREATE INDEX idx_recall_budget_ticks_ts ON recall_budget_ticks(ts DESC);

-- ---- store/cooldown_suppressions.py ----

CREATE TABLE cooldown_suppressions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,                 -- ISO8601 of the suppressed intent's recognition (intent.ts)
    kind TEXT NOT NULL,
    scope TEXT NOT NULL,
    confidence REAL NOT NULL DEFAULT 0.0,
    cooldown_until TEXT,              -- ISO8601 when the cooldown that dropped it expires (NULL if unknown)
    created_at TEXT NOT NULL          -- ISO8601 when the suppression was recorded
);

CREATE INDEX idx_cooldown_suppressions_ts ON cooldown_suppressions(ts DESC);

-- ---- store/intent_fold_ticks.py ----

CREATE TABLE intent_fold_ticks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,                 -- ISO8601 fold time
    scope TEXT NOT NULL,              -- the folding intent's scope (session-* / fast-K1 / …)
    kind TEXT NOT NULL,               -- the intent kind that folded (meeting/reminder/…)
    target_id INTEGER,                -- the existing intents row it folded ONTO (NULL if a bare dedup hit)
    outcome TEXT NOT NULL,            -- fold | updated (material re-recognition) | skipped (pure dup)
    created_at TEXT NOT NULL
);

CREATE INDEX idx_intent_fold_ticks_kind ON intent_fold_ticks(kind);

CREATE INDEX idx_intent_fold_ticks_ts ON intent_fold_ticks(ts DESC);

-- ---- store/schema_faces.py ----

CREATE TABLE schema_faces (
    face_id      TEXT PRIMARY KEY,
    level        INTEGER NOT NULL DEFAULT 1,   -- 1=面, 2=体（同表递归，高一层同一操作）
    parent_face  TEXT,                          -- §1.5 rollup：面归体、体锚 USER
    signature    TEXT NOT NULL DEFAULT '',      -- 签名（md 投影的中心命题）
    members      TEXT NOT NULL DEFAULT '[]',    -- 足迹：成员键 JSON（最新快照）
    footprints   TEXT NOT NULL DEFAULT '[]',    -- 最近 N 次足迹快照（重采样闸的输入）
    provenance   TEXT NOT NULL,                 -- mined | emergent | both（双信号=转正门槛）
    observations INTEGER NOT NULL DEFAULT 1,    -- 证据棘轮（每次 record +1）
    confidence   REAL NOT NULL DEFAULT 0.5,     -- 单调 MAX
    status       TEXT NOT NULL,                 -- MemoryStatus: shadow|active|superseded|archived
    valid_from   TEXT NOT NULL,
    valid_to     TEXT,
    created_at   TEXT NOT NULL
, anchors TEXT NOT NULL DEFAULT '[]');

CREATE INDEX ix_faces_status ON schema_faces(status, level);

-- ---- evomem/store.py ----

CREATE TABLE evo_nodes (
    node_id       TEXT NOT NULL,
    user_id       TEXT NOT NULL DEFAULT 'default',
    agent_id      TEXT NOT NULL DEFAULT 'default',
    content       TEXT NOT NULL,
    layer         TEXT NOT NULL,
    supersedes    TEXT NOT NULL DEFAULT '[]',
    superseded_by TEXT NOT NULL DEFAULT '[]',
    is_latest     INTEGER NOT NULL DEFAULT 1,
    status        TEXT NOT NULL DEFAULT 'active',
    memory_at     TEXT,
    gmt_created   TEXT,
    file_name     TEXT NOT NULL DEFAULT '',
    tags          TEXT NOT NULL DEFAULT '',
    refined_from  TEXT,
    abstracted_from TEXT NOT NULL DEFAULT '[]',
    confidence    TEXT,
    conflicted    INTEGER NOT NULL DEFAULT 0,
    occurred_at   TEXT,
    schema_summary TEXT,
    schema_inferences TEXT,
    schema_confidence REAL,
    valid_from    TEXT,
    valid_until   TEXT,
    PRIMARY KEY (node_id, user_id, agent_id)
);

CREATE INDEX idx_evo_nodes_latest ON evo_nodes(user_id, agent_id, is_latest, status);

CREATE INDEX idx_evo_nodes_scope ON evo_nodes(user_id, agent_id);

-- ---- evomem/integrity.py ----

CREATE TABLE integrity_check_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,                 -- ISO8601 check time
    day TEXT NOT NULL,                -- local YYYY-MM-DD
    source TEXT NOT NULL,             -- startup | daily-tick | ...
    violation_count INTEGER NOT NULL, -- REAL findings only (injected drills excluded)
    structural_count INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX idx_integrity_check_runs_day ON integrity_check_runs(day DESC);
