-- Generated by scripts/regen_db_schema.py — DO NOT EDIT.
-- Regenerate after changing any store DDL:
--
--     uv run python scripts/regen_db_schema.py
--
-- Source of truth stays in the per-module stores (CREATE TABLE IF NOT
-- EXISTS + per-module migrates); this file is the committed whole-picture
-- reference, guarded by tests/test_db_schema_drift.py.

-- ============================================================
-- index.db — the single main store (~/.persome/index.db, WAL)
-- ============================================================

-- ---- store/fts.py connect() — core schema + modules ensured on every connect ----

CREATE TABLE captures (
    rowid INTEGER PRIMARY KEY AUTOINCREMENT,
    id TEXT UNIQUE NOT NULL,
    timestamp TEXT NOT NULL,
    app_name TEXT,
    bundle_id TEXT,
    window_title TEXT,
    focused_role TEXT,
    focused_value TEXT,
    visible_text TEXT,
    url TEXT
);

CREATE VIRTUAL TABLE captures_fts USING fts5(
    app_name, window_title, focused_value, visible_text, url,
    content='captures', content_rowid='rowid',
    tokenize='unicode61 remove_diacritics 2'
);

CREATE VIRTUAL TABLE entries USING fts5(
    id UNINDEXED,
    path UNINDEXED,
    prefix UNINDEXED,
    timestamp UNINDEXED,
    tags,
    content,
    superseded UNINDEXED,
    tokenize = 'unicode61 remove_diacritics 2'
);

CREATE TABLE entry_metadata (
            entry_id    TEXT PRIMARY KEY,
            confidence  TEXT,
            conflicted  INTEGER NOT NULL DEFAULT 0,
            occurred_at TEXT
        );

CREATE TABLE entry_retrieval_stats (
    entry_id TEXT PRIMARY KEY,
    retrieval_count INTEGER NOT NULL DEFAULT 0,
    last_retrieved_at TEXT
);

CREATE TABLE entry_temporal (
            entry_id   TEXT PRIMARY KEY,
            valid_from TEXT NOT NULL,
            valid_until TEXT
        );

CREATE TABLE entry_vectors (
            entry_id    TEXT PRIMARY KEY,
            dim         INTEGER NOT NULL,
            model       TEXT NOT NULL,
            vector      BLOB NOT NULL,
            embedded_at TEXT NOT NULL
        );

CREATE TABLE files (
    path TEXT PRIMARY KEY,
    prefix TEXT,
    description TEXT,
    tags TEXT,
    status TEXT,
    entry_count INTEGER,
    created TEXT,
    updated TEXT,
    needs_compact INTEGER DEFAULT 0
);

CREATE TABLE projection_state (
    file_name    TEXT PRIMARY KEY,
    content_hash TEXT NOT NULL,
    projected_at TEXT NOT NULL
);

CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    start_time TEXT NOT NULL,
    end_time TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TEXT,
    last_error TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    flush_end TEXT,
    classified_end TEXT,
    pattern_detected_end TEXT,
    delta_end TEXT,
    modeled_at TEXT
);

CREATE TABLE sqlite_sequence(name,seq);

CREATE TABLE system_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE timeline_blocks (
    id TEXT PRIMARY KEY,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    timezone TEXT NOT NULL DEFAULT '',
    entries TEXT NOT NULL,
    apps_used TEXT NOT NULL,
    capture_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    skill_hints TEXT NOT NULL DEFAULT '[]',
    action_trace TEXT NOT NULL DEFAULT '[]',
    focus_excerpt TEXT NOT NULL DEFAULT '',
    focus_structured TEXT NOT NULL DEFAULT '',
    attention_surface TEXT NOT NULL DEFAULT '',
    attention_confidence REAL NOT NULL DEFAULT 0.0,
    attention_rung TEXT NOT NULL DEFAULT '',
    UNIQUE(start_time, end_time)
);

CREATE TABLE vector_queue (
            entry_id    TEXT PRIMARY KEY,
            enqueued_at TEXT NOT NULL
        );

CREATE INDEX idx_captures_app ON captures(app_name);

CREATE INDEX idx_captures_ts  ON captures(timestamp);

CREATE INDEX idx_files_prefix ON files(prefix);

CREATE INDEX idx_files_status ON files(status);

CREATE INDEX idx_sessions_retry ON sessions(next_retry_at)
    WHERE status = 'failed';

CREATE INDEX idx_sessions_start ON sessions(start_time);

CREATE INDEX idx_sessions_status ON sessions(status);

CREATE INDEX idx_tlb_end ON timeline_blocks(end_time);

CREATE INDEX idx_tlb_start ON timeline_blocks(start_time);

CREATE TRIGGER captures_ad AFTER DELETE ON captures BEGIN
    INSERT INTO captures_fts(captures_fts, rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES ('delete', old.rowid, old.app_name, old.window_title, old.focused_value, old.visible_text, old.url);
END;

CREATE TRIGGER captures_ai AFTER INSERT ON captures BEGIN
    INSERT INTO captures_fts(rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES (new.rowid, new.app_name, new.window_title, new.focused_value, new.visible_text, new.url);
END;

CREATE TRIGGER captures_au AFTER UPDATE ON captures BEGIN
    INSERT INTO captures_fts(captures_fts, rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES ('delete', old.rowid, old.app_name, old.window_title, old.focused_value, old.visible_text, old.url);
    INSERT INTO captures_fts(rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES (new.rowid, new.app_name, new.window_title, new.focused_value, new.visible_text, new.url);
END;

-- ---- store/relation_edges.py ----

CREATE TABLE relation_edges (
    edge_id      TEXT PRIMARY KEY,
    src_identity TEXT NOT NULL,          -- stable canonical identity, never a version node ID
    dst_identity TEXT NOT NULL,
    predicate    TEXT NOT NULL,          -- one closed-set predicate
    label        TEXT,                   -- open-text relation semantics
    valid_from   TEXT NOT NULL,          -- validity start in ISO 8601
    valid_to     TEXT,                   -- NULL while currently valid
    provenance   TEXT NOT NULL,          -- 'user_committed' | 'inferred'
    confidence   REAL NOT NULL,
    quote        TEXT,                   -- short source excerpt supporting the relation
    status       TEXT NOT NULL,          -- MemoryStatus: 'shadow'|'active'|'superseded'|'archived'
    created_at   TEXT NOT NULL,          -- immutable transaction time
    observations INTEGER NOT NULL DEFAULT 1,  -- monotone supporting-evidence count
    last_observed_at TEXT,               -- latest reinforcement in ISO 8601
    recall_count INTEGER NOT NULL DEFAULT 0  -- increments when a delivered chain uses this edge
, src_kind TEXT, dst_kind TEXT, polarity TEXT NOT NULL DEFAULT '0', source_kind TEXT, source_id TEXT, source_receipt TEXT);

CREATE INDEX ix_edges_dst ON relation_edges(dst_identity, valid_from);

CREATE INDEX ix_edges_src ON relation_edges(src_identity, valid_from);

-- ---- store/contradictions.py ----

CREATE TABLE memory_contradictions (
    pair_key    TEXT PRIMARY KEY,   -- sorted "a_id|b_id" — unordered-pair identity
    a_id        TEXT NOT NULL,
    b_id        TEXT NOT NULL,
    path        TEXT NOT NULL,      -- the memory file both facts live in
    a_body      TEXT NOT NULL,
    b_body      TEXT NOT NULL,
    reason      TEXT NOT NULL,      -- the judge's one-line why
    status      TEXT NOT NULL,      -- open | resolved | dismissed
    keep_id     TEXT,               -- resolve verdict: the entry the human kept
    created_at  TEXT NOT NULL,
    resolved_at TEXT
);

-- ---- store/memory_deltas.py ----

CREATE TABLE memory_deltas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    created_at TEXT NOT NULL,            -- ISO8601 consolidation time
    model TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'shadow',
    payload TEXT NOT NULL DEFAULT '{}',  -- post-gate delta JSON
    dropped INTEGER NOT NULL DEFAULT 0,  -- items removed by the deterministic gates
    apply_status TEXT NOT NULL DEFAULT 'unknown',
    window_start TEXT NOT NULL DEFAULT '',
    window_end TEXT NOT NULL DEFAULT '',
    is_final INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX idx_memory_deltas_created ON memory_deltas(created_at DESC);

CREATE INDEX idx_memory_deltas_session ON memory_deltas(session_id);

-- ---- store/parser_ticks.py ----

CREATE TABLE parser_ticks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,              -- ISO8601 window time (block start)
    bundle_id TEXT NOT NULL,       -- app bundle the outcome is attributed to
    outcome TEXT NOT NULL,         -- 'hit' | 'miss' | 'fallback'
    created_at TEXT NOT NULL
);

CREATE INDEX idx_parser_ticks_ts ON parser_ticks(ts DESC);

-- ---- store/schema_faces.py ----

CREATE TABLE schema_faces (
    face_id      TEXT PRIMARY KEY,
    level        INTEGER NOT NULL DEFAULT 1,   -- 1=Face, 2=Volume, 3=Root
    parent_face  TEXT,                          -- Face-to-Volume or Volume-to-Root rollup
    signature    TEXT NOT NULL DEFAULT '',      -- central proposition in Markdown projection
    members      TEXT NOT NULL DEFAULT '[]',    -- latest member-key snapshot as JSON
    footprints   TEXT NOT NULL DEFAULT '[]',    -- recent member snapshots for stability gate
    provenance   TEXT NOT NULL,                 -- mined | emergent | both
    observations INTEGER NOT NULL DEFAULT 1,    -- monotone evidence count
    confidence   REAL NOT NULL DEFAULT 0.5,     -- monotone maximum
    status       TEXT NOT NULL,                 -- MemoryStatus: shadow|active|superseded|archived
    valid_from   TEXT NOT NULL,
    valid_to     TEXT,
    created_at   TEXT NOT NULL
, anchors TEXT NOT NULL DEFAULT '[]');

CREATE INDEX ix_faces_status ON schema_faces(status, level);

-- ---- evomem/store.py ----

CREATE TABLE evo_nodes (
    node_id       TEXT NOT NULL,
    user_id       TEXT NOT NULL DEFAULT 'default',
    agent_id      TEXT NOT NULL DEFAULT 'default',
    content       TEXT NOT NULL,
    layer         TEXT NOT NULL,
    supersedes    TEXT NOT NULL DEFAULT '[]',
    superseded_by TEXT NOT NULL DEFAULT '[]',
    is_latest     INTEGER NOT NULL DEFAULT 1,
    status        TEXT NOT NULL DEFAULT 'active',
    memory_at     TEXT,
    gmt_created   TEXT,
    file_name     TEXT NOT NULL DEFAULT '',
    tags          TEXT NOT NULL DEFAULT '',
    refined_from  TEXT,
    abstracted_from TEXT NOT NULL DEFAULT '[]',
    confidence    TEXT,
    conflicted    INTEGER NOT NULL DEFAULT 0,
    occurred_at   TEXT,
    schema_summary TEXT,
    schema_inferences TEXT,
    schema_confidence REAL,
    valid_from    TEXT,
    valid_until   TEXT,
    PRIMARY KEY (node_id, user_id, agent_id)
);

CREATE INDEX idx_evo_nodes_latest ON evo_nodes(user_id, agent_id, is_latest, status);

CREATE INDEX idx_evo_nodes_scope ON evo_nodes(user_id, agent_id);

-- ---- evomem/integrity.py ----

CREATE TABLE integrity_check_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,                 -- ISO8601 check time
    day TEXT NOT NULL,                -- local YYYY-MM-DD
    source TEXT NOT NULL,             -- startup | daily-tick | ...
    violation_count INTEGER NOT NULL, -- REAL findings only (injected drills excluded)
    structural_count INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX idx_integrity_check_runs_day ON integrity_check_runs(day DESC);
