-- Generated by scripts/regen_db_schema.py — DO NOT EDIT.
-- Regenerate after changing any store DDL:
--
--     uv run python scripts/regen_db_schema.py
--
-- Source of truth stays in the per-module stores (CREATE TABLE IF NOT
-- EXISTS + per-module migrates); this file is the committed whole-picture
-- reference, guarded by tests/test_db_schema_drift.py.

-- ============================================================
-- index.db — the single main store (~/.persome/index.db, WAL)
-- ============================================================

-- ---- store/fts.py connect() — core schema + modules ensured on every connect ----

CREATE TABLE agent_run_events (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id  INTEGER NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
    ts      TEXT NOT NULL,
    type    TEXT NOT NULL,
    payload TEXT NOT NULL
);

CREATE TABLE agent_runs (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    kind            TEXT NOT NULL,
    title           TEXT NOT NULL DEFAULT '',
    status          TEXT NOT NULL,
    trigger         TEXT NOT NULL,
    dispatch_source TEXT NOT NULL DEFAULT 'system',
    enqueued_at     TEXT NOT NULL,
    started_at      TEXT,
    ended_at        TEXT,
    progress        REAL,
    progress_label  TEXT NOT NULL DEFAULT '',
    eta_seconds     INTEGER,
    payload         TEXT NOT NULL DEFAULT '{}',
    summary         TEXT NOT NULL DEFAULT '',
    result_refs     TEXT NOT NULL DEFAULT '[]',
    error           TEXT NOT NULL DEFAULT '',
    skipped_reason  TEXT NOT NULL DEFAULT ''
);

CREATE TABLE book_chapters (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    title       TEXT NOT NULL,
    subtitle    TEXT NOT NULL DEFAULT '',
    session_ids TEXT NOT NULL DEFAULT '[]',  -- JSON array of chat session ids
    edited      INTEGER NOT NULL DEFAULT 0,  -- 1 once the user renamed it
    created_at  TEXT NOT NULL
);

CREATE TABLE captures (
    rowid INTEGER PRIMARY KEY AUTOINCREMENT,
    id TEXT UNIQUE NOT NULL,
    timestamp TEXT NOT NULL,
    app_name TEXT,
    bundle_id TEXT,
    window_title TEXT,
    focused_role TEXT,
    focused_value TEXT,
    visible_text TEXT,
    url TEXT
);

CREATE VIRTUAL TABLE captures_fts USING fts5(
    app_name, window_title, focused_value, visible_text, url,
    content='captures', content_rowid='rowid',
    tokenize='unicode61 remove_diacritics 2'
);

CREATE TABLE dream_events (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    run_id  INTEGER NOT NULL REFERENCES dream_runs(id) ON DELETE CASCADE,
    ts      TEXT NOT NULL,
    type    TEXT NOT NULL,
    payload TEXT NOT NULL
);

CREATE TABLE dream_runs (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    started_at      TEXT NOT NULL,
    ended_at        TEXT,
    trigger         TEXT NOT NULL,              -- 'manual' | 'daily-tick'
    status          TEXT NOT NULL,              -- 'running' | 'committed' | 'skipped' | 'failed'
    summary         TEXT NOT NULL DEFAULT '',
    written_count   INTEGER NOT NULL DEFAULT 0,
    iterations      INTEGER NOT NULL DEFAULT 0,
    error           TEXT NOT NULL DEFAULT '',
    skipped_reason  TEXT NOT NULL DEFAULT '',
    written_ids     TEXT NOT NULL DEFAULT '[]', -- JSON array of memory entry ids
    created_paths   TEXT NOT NULL DEFAULT '[]'  -- JSON array of file paths
);

CREATE VIRTUAL TABLE entries USING fts5(
    id UNINDEXED,
    path UNINDEXED,
    prefix UNINDEXED,
    timestamp UNINDEXED,
    tags,
    content,
    superseded UNINDEXED,
    tokenize = 'unicode61 remove_diacritics 2'
);

CREATE TABLE entry_metadata (
            entry_id    TEXT PRIMARY KEY,
            confidence  TEXT,
            conflicted  INTEGER NOT NULL DEFAULT 0,
            occurred_at TEXT
        );

CREATE TABLE entry_retrieval_stats (
    entry_id TEXT PRIMARY KEY,
    retrieval_count INTEGER NOT NULL DEFAULT 0,
    last_retrieved_at TEXT
);

CREATE TABLE entry_temporal (
            entry_id   TEXT PRIMARY KEY,
            valid_from TEXT NOT NULL,
            valid_until TEXT
        );

CREATE TABLE entry_vectors (
            entry_id    TEXT PRIMARY KEY,
            dim         INTEGER NOT NULL,
            model       TEXT NOT NULL,
            vector      BLOB NOT NULL,
            embedded_at TEXT NOT NULL
        );

CREATE TABLE files (
    path TEXT PRIMARY KEY,
    prefix TEXT,
    description TEXT,
    tags TEXT,
    status TEXT,
    entry_count INTEGER,
    created TEXT,
    updated TEXT,
    needs_compact INTEGER DEFAULT 0
);

CREATE TABLE highlights (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    quote       TEXT NOT NULL,
    source_ref  TEXT NOT NULL DEFAULT '',  -- source page id or chat session id
    created_at  TEXT NOT NULL
);

CREATE TABLE intents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,                 -- ISO8601 recognition time
    scope TEXT NOT NULL,              -- scene id: 'timeline' | <meeting-id> | ...
    kind TEXT NOT NULL,               -- open string; seed: meeting|calendar|reminder
    confidence REAL NOT NULL DEFAULT 0.0,
    status TEXT NOT NULL DEFAULT 'open',  -- open | armed | consumed | dismissed | expired | resolved | completed | failed
    rationale TEXT NOT NULL DEFAULT '',
    payload TEXT NOT NULL DEFAULT '{}',   -- JSON: kind-specific fields
    evidence TEXT NOT NULL DEFAULT '[]',  -- JSON: provenance list
    dedup_key TEXT NOT NULL DEFAULT '',   -- scope|kind|when_text|with — for idempotent persist
    created_at TEXT NOT NULL,
    dismissed_at TEXT,                    -- ISO8601 when the row transitioned to status='dismissed' (NULL otherwise); the kind-cooldown clock (#533) anchors on this, NOT ts (recognition time)
    completed_at TEXT,                    -- ISO8601 when the row transitioned to status IN (completed,failed) (NULL otherwise); reverse-loop: the accept→completed positive prior (_completed_prior) anchors on this, NOT ts

    fire_on TEXT NOT NULL DEFAULT '',     -- event-based intent: trigger event key ('' == immediate)
    fire_config TEXT NOT NULL DEFAULT '{}',  -- JSON: trigger params (bundle_id/app/...)
    fired_at TEXT,                        -- ISO8601 when the trigger fired (NULL until then)
    schema_sources TEXT NOT NULL DEFAULT '[]',  -- JSON: schema-*.md files injected when recognized (R4 provenance)
    resolved_at TEXT,                     -- ISO8601 deterministic parse of payload.when_text anchored at ts (NULL = unparsed)
    valid_until TEXT,                     -- ISO8601 expiry: resolved_at(+end) + kind grace (NULL = never expires)
    source_capture TEXT,                  -- capture-buffer file stem this intent was recognized FROM (#7 provenance; NULL = none/legacy → time-window join fallback)
    resolution_outcome TEXT,              -- evidence-driven auto-close outcome (done|rejected|superseded; NULL unless status='resolved')
    resolution_quote TEXT                 -- ≤120-char supporting quote for the evidence-driven close (NULL unless status='resolved')
);

CREATE TABLE projection_state (
    file_name    TEXT PRIMARY KEY,
    content_hash TEXT NOT NULL,
    projected_at TEXT NOT NULL
);

CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    start_time TEXT NOT NULL,
    end_time TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TEXT,
    last_error TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    flush_end TEXT,
    classified_end TEXT,
    pattern_detected_end TEXT,
    active_tick_bookmark TEXT
, total_cost_usd REAL, recognized_final_at TEXT);

CREATE TABLE sqlite_sequence(name,seq);

CREATE TABLE system_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE timeline_blocks (
    id TEXT PRIMARY KEY,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    timezone TEXT NOT NULL DEFAULT '',
    entries TEXT NOT NULL,
    apps_used TEXT NOT NULL,
    capture_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    helpful_intent_tags TEXT NOT NULL DEFAULT '[]',
    skill_hints TEXT NOT NULL DEFAULT '[]',
    action_trace TEXT NOT NULL DEFAULT '[]',
    focus_excerpt TEXT NOT NULL DEFAULT '',
    focus_structured TEXT NOT NULL DEFAULT '',
    attention_surface TEXT NOT NULL DEFAULT '',
    attention_confidence REAL NOT NULL DEFAULT 0.0,
    attention_rung TEXT NOT NULL DEFAULT '',
    UNIQUE(start_time, end_time)
);

CREATE TABLE vector_queue (
            entry_id    TEXT PRIMARY KEY,
            enqueued_at TEXT NOT NULL
        );

CREATE INDEX idx_agent_run_events_run ON agent_run_events(run_id, id);

CREATE INDEX idx_agent_runs_kind_time  ON agent_runs(kind, enqueued_at DESC);

CREATE INDEX idx_agent_runs_started    ON agent_runs(started_at DESC);

CREATE INDEX idx_agent_runs_status_enq ON agent_runs(status, enqueued_at);

CREATE INDEX idx_book_chapters_created
    ON book_chapters(created_at DESC);

CREATE INDEX idx_captures_app ON captures(app_name);

CREATE INDEX idx_captures_ts  ON captures(timestamp);

CREATE INDEX idx_dream_events_run
    ON dream_events(run_id, id);

CREATE INDEX idx_dream_runs_started
    ON dream_runs(started_at DESC);

CREATE INDEX idx_files_prefix ON files(prefix);

CREATE INDEX idx_files_status ON files(status);

CREATE INDEX idx_highlights_created
    ON highlights(created_at DESC);

CREATE INDEX idx_intents_dedup ON intents(dedup_key);

CREATE INDEX idx_intents_scope_ts ON intents(scope, ts DESC);

CREATE INDEX idx_intents_source_capture ON intents(source_capture);

CREATE INDEX idx_intents_status_ts ON intents(status, ts DESC);

CREATE INDEX idx_sessions_retry ON sessions(next_retry_at)
    WHERE status = 'failed';

CREATE INDEX idx_sessions_start ON sessions(start_time);

CREATE INDEX idx_sessions_status ON sessions(status);

CREATE INDEX idx_tlb_end ON timeline_blocks(end_time);

CREATE INDEX idx_tlb_start ON timeline_blocks(start_time);

CREATE TRIGGER captures_ad AFTER DELETE ON captures BEGIN
    INSERT INTO captures_fts(captures_fts, rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES ('delete', old.rowid, old.app_name, old.window_title, old.focused_value, old.visible_text, old.url);
END;

CREATE TRIGGER captures_ai AFTER INSERT ON captures BEGIN
    INSERT INTO captures_fts(rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES (new.rowid, new.app_name, new.window_title, new.focused_value, new.visible_text, new.url);
END;

CREATE TRIGGER captures_au AFTER UPDATE ON captures BEGIN
    INSERT INTO captures_fts(captures_fts, rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES ('delete', old.rowid, old.app_name, old.window_title, old.focused_value, old.visible_text, old.url);
    INSERT INTO captures_fts(rowid, app_name, window_title, focused_value, visible_text, url)
    VALUES (new.rowid, new.app_name, new.window_title, new.focused_value, new.visible_text, new.url);
END;

-- ---- workthread/store.py ----

CREATE TABLE work_threads (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    goal TEXT NOT NULL DEFAULT '',
    origin_type TEXT NOT NULL DEFAULT 'self_initiated',
    origin_actor TEXT NOT NULL DEFAULT '',
    origin_evidence TEXT NOT NULL DEFAULT '[]',
    origin_at TEXT NOT NULL DEFAULT '',
    origin_intent_id INTEGER,
    status TEXT NOT NULL DEFAULT 'background',
    first_seen TEXT NOT NULL DEFAULT '',
    last_active TEXT NOT NULL DEFAULT '',
    total_active_minutes INTEGER NOT NULL DEFAULT 0,
    approximate INTEGER NOT NULL DEFAULT 0,
    bindings TEXT NOT NULL DEFAULT '[]',
    progress_notes TEXT NOT NULL DEFAULT '[]',
    confidence REAL NOT NULL DEFAULT 0.5,
    pinned INTEGER NOT NULL DEFAULT 0,
    user_corrected INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE workthread_labels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    day TEXT NOT NULL DEFAULT '',
    thread_id TEXT NOT NULL DEFAULT '',
    action TEXT NOT NULL,
    payload TEXT NOT NULL DEFAULT '{}',
    source TEXT NOT NULL DEFAULT ''
);

CREATE TABLE workthread_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    sub_tasks TEXT NOT NULL DEFAULT '[]',
    start_time TEXT NOT NULL DEFAULT '',
    end_time TEXT NOT NULL DEFAULT '',
    enqueued_at TEXT NOT NULL,
    consumed_at TEXT
);

CREATE TABLE workthread_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE workthread_ticks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,
    window_id TEXT NOT NULL DEFAULT '',
    sessions INTEGER NOT NULL DEFAULT 0,
    opens INTEGER NOT NULL DEFAULT 0,
    attaches INTEGER NOT NULL DEFAULT 0,
    revives INTEGER NOT NULL DEFAULT 0,
    completes INTEGER NOT NULL DEFAULT 0,
    merges INTEGER NOT NULL DEFAULT 0,
    disagreement INTEGER NOT NULL DEFAULT 0,
    outcome TEXT NOT NULL DEFAULT 'ok'
);

CREATE INDEX idx_work_threads_status ON work_threads(status, last_active DESC);

CREATE INDEX idx_workthread_labels_day ON workthread_labels(day, id);

CREATE INDEX idx_workthread_queue_pending
    ON workthread_queue(consumed_at, enqueued_at);

CREATE INDEX idx_workthread_ticks_ts ON workthread_ticks(ts DESC);

-- ---- store/relation_edges.py ----

CREATE TABLE relation_edges (
    edge_id      TEXT PRIMARY KEY,
    src_identity TEXT NOT NULL,          -- 稳定 identity（person_graph 规范名 / PROJECT slug），非版本 node_id
    dst_identity TEXT NOT NULL,
    predicate    TEXT NOT NULL,          -- 6 谓词闭集之一
    label        TEXT,                   -- 自由文本关系（开集语义）
    valid_from   TEXT NOT NULL,          -- 有效时间起（ISO8601）
    valid_to     TEXT,                   -- NULL = 当前有效
    provenance   TEXT NOT NULL,          -- 'user_committed' | 'inferred'
    confidence   REAL NOT NULL,
    quote        TEXT,                   -- ≤120 字支撑原文（证据）
    status       TEXT NOT NULL,          -- MemoryStatus: 'shadow'|'active'|'superseded'|'archived'
    created_at   TEXT NOT NULL,          -- 事务时间（版本轴，不可变）
    observations INTEGER NOT NULL DEFAULT 1,  -- 强度=支撑该关系的证据数（event 蒸馏计数，单调不减）
    last_observed_at TEXT,              -- 最近一次证据强化时刻（ISO8601）
    recall_count INTEGER NOT NULL DEFAULT 0  -- 读也是强化（§3.3 testing effect）：树链走过这条边即 +1
, src_kind TEXT, dst_kind TEXT, polarity TEXT NOT NULL DEFAULT '0');

CREATE INDEX ix_edges_dst ON relation_edges(dst_identity, valid_from);

CREATE INDEX ix_edges_src ON relation_edges(src_identity, valid_from);

-- ---- store/contradictions.py ----

CREATE TABLE memory_contradictions (
    pair_key    TEXT PRIMARY KEY,   -- sorted "a_id|b_id" — unordered-pair identity
    a_id        TEXT NOT NULL,
    b_id        TEXT NOT NULL,
    path        TEXT NOT NULL,      -- the memory file both facts live in
    a_body      TEXT NOT NULL,
    b_body      TEXT NOT NULL,
    reason      TEXT NOT NULL,      -- the judge's one-line why
    status      TEXT NOT NULL,      -- open | resolved | dismissed
    keep_id     TEXT,               -- resolve verdict: the entry the human kept
    created_at  TEXT NOT NULL,
    resolved_at TEXT
);

-- ---- store/memory_deltas.py ----

CREATE TABLE memory_deltas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    created_at TEXT NOT NULL,            -- ISO8601 consolidation time
    model TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'shadow',
    payload TEXT NOT NULL DEFAULT '{}',  -- post-gate delta JSON
    dropped INTEGER NOT NULL DEFAULT 0   -- items removed by the deterministic gates
);

CREATE INDEX idx_memory_deltas_created ON memory_deltas(created_at DESC);

CREATE INDEX idx_memory_deltas_session ON memory_deltas(session_id);

-- ---- store/outcomes.py ----

CREATE TABLE outcomes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,                         -- ISO8601 outcome time (app-stamped)
    intent_id INTEGER,                        -- the intent this execution served (NULL if none)
    kind TEXT NOT NULL,                       -- intent kind: meeting|calendar|reminder|... (enum-ish)
    status TEXT NOT NULL,                     -- followup | supervised (which executor produced it)
    success INTEGER NOT NULL DEFAULT 0,       -- 0/1 — did it accomplish the accepted thing
    executor_tier TEXT,                       -- optional capability tier label (enum)
    artifact_verified INTEGER,                -- 0/1 — the produced artifact was verified (FollowUp)
    placed INTEGER,                           -- 0/1 — pasted into a focused field (never sent)
    awaited_confirm INTEGER,                  -- 0/1 — execution paused for a user confirm
    reschedule_suggested INTEGER,             -- 0/1 — a reschedule was proposed
    elapsed_ms INTEGER,                       -- wall-clock duration, ms
    created_at TEXT NOT NULL
);

CREATE INDEX idx_outcomes_kind ON outcomes(kind);

CREATE INDEX idx_outcomes_ts ON outcomes(ts DESC);

-- ---- store/parser_ticks.py ----

CREATE TABLE parser_ticks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,              -- ISO8601 window time (block start)
    bundle_id TEXT NOT NULL,       -- app bundle the outcome is attributed to
    outcome TEXT NOT NULL,         -- 'hit' | 'miss' | 'fallback'
    created_at TEXT NOT NULL
);

CREATE INDEX idx_parser_ticks_ts ON parser_ticks(ts DESC);

-- ---- store/recall_budget_ticks.py ----

CREATE TABLE recall_budget_ticks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,              -- ISO8601 assembly time
    scope TEXT NOT NULL,           -- recall scope (session-*, meeting-*, ...)
    max_chars INTEGER NOT NULL,    -- true assembly ceiling: main budget + the
                                   -- workthread layer's independent budget (#623)
    used INTEGER NOT NULL,         -- chars actually admitted across ALL layers,
                                   -- the workthread independent budget included (#623)
    layers TEXT NOT NULL DEFAULT '{}',  -- JSON {layer: {admitted, admitted_chars, rejected, rejected_chars}}
    squeezed INTEGER NOT NULL DEFAULT 0, -- 1 when ANY layer rejected at least one text
    hints TEXT NOT NULL DEFAULT '[]',   -- JSON list of the call's hint terms (debugging telemetry)
    created_at TEXT NOT NULL
);

CREATE INDEX idx_recall_budget_ticks_ts ON recall_budget_ticks(ts DESC);

-- ---- store/cooldown_suppressions.py ----

CREATE TABLE cooldown_suppressions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,                 -- ISO8601 of the suppressed intent's recognition (intent.ts)
    kind TEXT NOT NULL,
    scope TEXT NOT NULL,
    confidence REAL NOT NULL DEFAULT 0.0,
    cooldown_until TEXT,              -- ISO8601 when the cooldown that dropped it expires (NULL if unknown)
    created_at TEXT NOT NULL          -- ISO8601 when the suppression was recorded
);

CREATE INDEX idx_cooldown_suppressions_ts ON cooldown_suppressions(ts DESC);

-- ---- store/intent_fold_ticks.py ----

CREATE TABLE intent_fold_ticks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,                 -- ISO8601 fold time
    scope TEXT NOT NULL,              -- the folding intent's scope (session-* / fast-K1 / …)
    kind TEXT NOT NULL,               -- the intent kind that folded (meeting/reminder/…)
    target_id INTEGER,                -- the existing intents row it folded ONTO (NULL if a bare dedup hit)
    outcome TEXT NOT NULL,            -- fold | updated (material re-recognition) | skipped (pure dup)
    created_at TEXT NOT NULL
);

CREATE INDEX idx_intent_fold_ticks_kind ON intent_fold_ticks(kind);

CREATE INDEX idx_intent_fold_ticks_ts ON intent_fold_ticks(ts DESC);

-- ---- store/schema_faces.py ----

CREATE TABLE schema_faces (
    face_id      TEXT PRIMARY KEY,
    level        INTEGER NOT NULL DEFAULT 1,   -- 1=面, 2=体（同表递归，高一层同一操作）
    parent_face  TEXT,                          -- §1.5 rollup：面归体、体锚 USER
    signature    TEXT NOT NULL DEFAULT '',      -- 签名（md 投影的中心命题）
    members      TEXT NOT NULL DEFAULT '[]',    -- 足迹：成员键 JSON（最新快照）
    footprints   TEXT NOT NULL DEFAULT '[]',    -- 最近 N 次足迹快照（重采样闸的输入）
    provenance   TEXT NOT NULL,                 -- mined | emergent | both（双信号=转正门槛）
    observations INTEGER NOT NULL DEFAULT 1,    -- 证据棘轮（每次 record +1）
    confidence   REAL NOT NULL DEFAULT 0.5,     -- 单调 MAX
    status       TEXT NOT NULL,                 -- MemoryStatus: shadow|active|superseded|archived
    valid_from   TEXT NOT NULL,
    valid_to     TEXT,
    created_at   TEXT NOT NULL
, anchors TEXT NOT NULL DEFAULT '[]');

CREATE INDEX ix_faces_status ON schema_faces(status, level);

-- ---- memory/task_outcome.py ----

CREATE TABLE task_outcome_ingests (
    task_id TEXT PRIMARY KEY,       -- app task UUID — the idempotency key
    intent_id INTEGER,              -- the intent this execution served (NULL if none)
    entry_id TEXT,                  -- the written entry id (NULL when dropped by the PII gate)
    status TEXT NOT NULL,           -- ingested | dropped_pii
    ts TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- ---- evomem/store.py ----

CREATE TABLE evo_nodes (
    node_id       TEXT NOT NULL,
    user_id       TEXT NOT NULL DEFAULT 'default',
    agent_id      TEXT NOT NULL DEFAULT 'default',
    content       TEXT NOT NULL,
    layer         TEXT NOT NULL,
    supersedes    TEXT NOT NULL DEFAULT '[]',
    superseded_by TEXT NOT NULL DEFAULT '[]',
    is_latest     INTEGER NOT NULL DEFAULT 1,
    status        TEXT NOT NULL DEFAULT 'active',
    memory_at     TEXT,
    gmt_created   TEXT,
    file_name     TEXT NOT NULL DEFAULT '',
    tags          TEXT NOT NULL DEFAULT '',
    refined_from  TEXT,
    abstracted_from TEXT NOT NULL DEFAULT '[]',
    confidence    TEXT,
    conflicted    INTEGER NOT NULL DEFAULT 0,
    occurred_at   TEXT,
    schema_summary TEXT,
    schema_inferences TEXT,
    schema_confidence REAL,
    valid_from    TEXT,
    valid_until   TEXT,
    PRIMARY KEY (node_id, user_id, agent_id)
);

CREATE INDEX idx_evo_nodes_latest ON evo_nodes(user_id, agent_id, is_latest, status);

CREATE INDEX idx_evo_nodes_scope ON evo_nodes(user_id, agent_id);

-- ---- evomem/integrity.py ----

CREATE TABLE integrity_check_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT NOT NULL,                 -- ISO8601 check time
    day TEXT NOT NULL,                -- local YYYY-MM-DD
    source TEXT NOT NULL,             -- startup | daily-tick | ...
    violation_count INTEGER NOT NULL, -- REAL findings only (injected drills excluded)
    structural_count INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX idx_integrity_check_runs_day ON integrity_check_runs(day DESC);

-- ============================================================
-- meeting_*.db — separate per-meeting transcript stores
-- ============================================================

-- ---- meeting/store.py ----

CREATE TABLE pushes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp REAL NOT NULL,
                text TEXT NOT NULL
            );

CREATE TABLE sqlite_sequence(name,seq);

CREATE TABLE transcripts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp REAL NOT NULL,
                source TEXT NOT NULL,
                text TEXT NOT NULL,
                sentence_id INTEGER DEFAULT 0
            );

CREATE INDEX idx_transcripts_timestamp ON transcripts(timestamp);
